#include "trishula/maneuver/physical_lunar_powered_descent.h"
#include "trishula/maneuver/physical_lunar_terminal_descent.h"
#include "trishula/mission/physical_mission_execution.h"
#include <cmath>
#include <iomanip>
#include <iostream>
#include <stdexcept>
namespace { constexpr double mu=4.9048695e12,R=1.7374e6,MR=384400.0e3,MP=27.321661*86400.0,PI=3.14159265358979323846;
trishula::Vector3 mp(double t,double p){double th=p+2*PI*t/MP;return {MR*std::cos(th),MR*std::sin(th),0};}
trishula::Vector3 mv(double t,double p){double th=p+2*PI*t/MP,w=2*PI/MP;return {-MR*w*std::sin(th),MR*w*std::cos(th),0};}}
int main(){try{trishula::PhysicalMissionExecutionConfiguration mc{};mc.step_seconds=1;mc.earth_orbit_hold_seconds=10;mc.event_driven_physical_arc=true;mc.initial_mass_kg=90000.0;trishula::PhysicalMissionExecutionEngine m(mc);m.run_until_phase(trishula::MissionPhase::LunarOrbit,1000000U);(void)m.execute_lunar_orbit_insertion();(void)m.execute_lunar_orbit_operations();if(!m.execute_lunar_descent_preparation().descent_ready)throw std::runtime_error("V0.9.45 baseline is not descent-ready");double p=m.tli_plan().required_lunar_phase_angle_rad;trishula::PhysicalLunarPoweredDescentConfiguration c{};c.initiation_altitude_meters=10000;c.powered_descent_checkpoint_altitude_meters=2000;c.deorbit_target_perilune_altitude_meters=-20000;c.control_step_seconds=.25;c.maximum_descent_duration_seconds=5000;c.maximum_deorbit_delta_v_m_per_s=100;trishula::PhysicalLunarPoweredDescentExecutor e(c,[p](double t){return mp(t,p);},[p](double t){return mv(t,p);},mu,R);auto v46=e.execute(m.simulation());if(!v46.powered_descent_active)throw std::runtime_error("V0.9.46 baseline is not active");trishula::PhysicalLunarTerminalDescentConfiguration tc{};tc.minimum_propellant_reserve_kg=100;trishula::PhysicalLunarTerminalDescentExecutor te(tc,[p](double t){return mp(t,p);},[p](double t){return mv(t,p);},mu,R);auto v47=te.execute(m.simulation());std::cout<<std::fixed<<std::setprecision(6)<<"TRISHULA V0.9.47 - Physical Powered Descent Continuation\n==============================================================\n  V0.9.46 baseline              : PASS\n  initial altitude               : "<<v47.initial_altitude_meters<<" m\n  final altitude                 : "<<v47.final_altitude_meters<<" m\n  propellant consumed            : "<<v47.propellant_consumed_kg<<" kg\n  remaining propellant           : "<<v47.remaining_propellant_kg<<" kg\n  terminal descent active        : "<<(v47.terminal_descent_active?"PASS":"FAIL")<<"\n";return v47.terminal_descent_active?0:1;}catch(const std::exception&x){std::cout<<"TRISHULA V0.9.47 - Physical Powered Descent Continuation\n==============================================================\n  V0.9.46 baseline              : PASS\n  terminal descent status        : BLOCKED\n  reason                         : "<<x.what()<<"\n";return 2;}}
