#pragma once
#include <cstdint>
#include <string>
#include "trishula/landing/lunar_terrain.h"
#include "trishula/maneuver/lunar_orbit_insertion.h"
#include "trishula/maneuver/trans_lunar_injection.h"
#include "trishula/rover/surface_rover.h"
#include "trishula/surface/post_landing_operations.h"
namespace trishula {
enum class MissionPhase { Launch, EarthOrbit, TransLunarInjection, LunarCruise, LunarOrbit, Descent, Landing, RoverDeployment, SurfaceOperations, Complete, Fault };
struct MissionExecutionConfiguration { double step_seconds{1.0}; double launch_duration_seconds{120.0}; double earth_orbit_duration_seconds{60.0}; double tli_duration_seconds{30.0}; double lunar_cruise_duration_seconds{900.0}; double lunar_orbit_duration_seconds{120.0}; double descent_duration_seconds{300.0}; double landing_duration_seconds{30.0}; double rover_deployment_duration_seconds{30.0}; double surface_target_x_m{-200.0}; double surface_target_y_m{0.0}; };
struct MissionExecutionSnapshot { std::string mission_id{"TRISHULA"}; MissionPhase phase{MissionPhase::Launch}; double mission_time_seconds{0.0}; double phase_elapsed_seconds{0.0}; double phase_progress{0.0}; double altitude_m{0.0}; double velocity_m_per_s{0.0}; double distance_to_moon_m{0.0}; double spacecraft_x_m{0.0}; double spacecraft_y_m{0.0}; double battery_soc{1.0}; double propellant_fraction{1.0}; double rover_x_m{0.0}; double rover_y_m{0.0}; double rover_speed_m_per_s{0.0}; bool landed{false}; bool rover_deployed{false}; bool rover_surface_ready{false}; bool rover_mission_complete{false}; std::uint64_t telemetry_sequence{0}; std::string mode{"LAUNCH"}; };
class MissionExecutionEngine { public: explicit MissionExecutionEngine(MissionExecutionConfiguration configuration = {}); void reset(); void step(); void run_until_complete(std::uint64_t max_steps = 100000); [[nodiscard]] const MissionExecutionSnapshot& snapshot() const noexcept; [[nodiscard]] MissionPhase phase() const noexcept; [[nodiscard]] bool complete() const noexcept; [[nodiscard]] const TransLunarInjectionPlan& tli_plan() const noexcept; [[nodiscard]] const LunarOrbitInsertionPlan& loi_plan() const noexcept; [[nodiscard]] const RoverState& rover_state() const noexcept; [[nodiscard]] const SurfaceLanderState& lander_state() const noexcept; [[nodiscard]] static const char* phase_name(MissionPhase phase) noexcept; private: void enter_phase(MissionPhase phase); void update_phase(); void update_flight_state(); void update_descent(); void update_landing(); void update_surface(); void refresh_snapshot(); MissionExecutionConfiguration configuration_{}; MissionPhase phase_{MissionPhase::Launch}; double mission_time_seconds_{0.0}; double phase_elapsed_seconds_{0.0}; std::uint64_t telemetry_sequence_{0}; TransLunarInjectionPlan tli_plan_{}; LunarOrbitInsertionPlan loi_plan_{}; LunarTerrainMap terrain_{0.0}; SurfaceRover rover_{}; RoverState rover_state_{}; RoverMissionTarget rover_target_{}; PostLandingOperations post_landing_{}; SurfaceLanderState lander_state_{}; MissionExecutionSnapshot snapshot_{}; };
} // namespace trishula
